### ISSUE TITLE
1.8.0 breaks swagger (2.3.1)

### ISSUE THREAD

**Issue by AndreKlang** [Ethan3600/EthanYehuda_CronjobManager#115]
**Describe the bug**
Swagger breaks with this exception:

```
<response>
<message>
Notice: Undefined offset: 1 in /var/www/html/vendor/magento/framework/Reflection/TypeProcessor.php on line 896
</message>
<trace>
#0 /var/www/html/vendor/magento/framework/Reflection/TypeProcessor.php(896): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/var/www/html/v...', 896, Array) #1 /var/www/html/vendor/magento/framework/Reflection/TypeProcessor.php(677): Magento\Framework\Reflection\TypeProcessor->getParamDocBlockTag(Object(Zend\Code\Reflection\ParameterReflection)) #2 /var/www/html/vendor/magento/module-webapi/Model/Config/ClassReflector.php(93): Magento\Framework\Reflection\TypeProcessor->getParamDescription(Object(Zend\Code\Reflection\ParameterReflection)) #3 /var/www/html/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection)) #4 /var/www/html/vendor/magento/module-webapi/Model/ServiceMetadata.php(127): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('EthanYehuda\\Cro...', Array) #5 /var/www/html/vendor/magento/module-webapi/Model/ServiceMetadata.php(156): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata() #6 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Model\ServiceMetadata->getServicesConfig() #7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callParent('getServicesConf...', Array) #8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Model\ServiceMetadata\Interceptor->Magento\Framework\Interception\{closure}() #9 /var/www/html/generated/code/Magento/Webapi/Model/ServiceMetadata/Interceptor.php(26): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callPlugins('getServicesConf...', Array, Array) #10 /var/www/html/vendor/magento/module-webapi/Model/Rest/Swagger/Generator.php(923): Magento\Webapi\Model\ServiceMetadata\Interceptor->getServicesConfig() #11 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SchemaRequestProcessor.php(53): Magento\Webapi\Model\Rest\Swagger\Generator->getListOfServices() #12 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SchemaRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy)) #13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http)) #14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array) #15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #16 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array) #17 /var/www/html/vendor/magento/framework/App/Http.php(136): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #18 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch() #19 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch() #20 /var/www/html/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #21 {main}
</trace>
</response>
```

**To Reproduce**
1. Go to: https://your.domain/swagger
2. You won't be able to use swagger at all

**See the exception**
1. Go to https://your.domain/rest/all/schema?services=all
2. You should *not* see a stacktrace

**Expected behavior**
You should be able to use swagger to see all endpoints

**Environment:**
 - Cron Job Manager Version 1.8.0
 - Magento Version 2.3.1
 - PHP Version 7.2
 - Developer mode ON

**Additional context**
version 1.7.1 work in the same environment

**Comment by Ethan3600** [comment]
Please upgrade to v1.8.1.

Going to close this out for now. Feel free to comment if there are still issues.
