### ISSUE TITLE
Unable to resolve the source file for .../toolbar.html

### ISSUE THREAD

**Issue by lfritsche** [Ethan3600/EthanYehuda_CronjobManager#13]
Hi @Ethan3600 

I'm seeing the following error using Version 0.2.1 with Magento 2.1.5

```
Unable to resolve the source file for 'adminhtml/Magento/backend/de_DE/cronjobManager/template/timeline/toolbar.html' #0 /html/******/vendor/magento/framework/App/StaticResource.php(97): Magento\Framework\View\Asset\File->getSourceFile() #1 /html/******/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch() #2 /html/******/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource)) #3 {main}
```

Would be great, if you could help me regarding this issue.

Cheers

**Comment by lfritsche** [comment]
Issue resolved by rebuilding static files again.
