### ISSUE TITLE
Warning: sprintf(): Too few arguments

### ISSUE THREAD

**Issue by refueledinc** [Ethan3600/EthanYehuda_CronjobManager#41]
While dispatching a failed cron, I received this error message. 
Cron Manager 1.3.3
Magento 2.2.3, Developer mode

```
1 exception(s):
Exception #0 (Exception): Warning: sprintf(): Too few arguments in [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Helper/Processor.php on line 111

Exception #0 (Exception): Warning: sprintf(): Too few arguments in [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Helper/Processor.php on line 111
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'sprintf(): Too ...', '/home/awningwor...', 111, Array)
#1 [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Helper/Processor.php(111): sprintf('Cron Job %s has...', 'elasticsuite_in...', 'Requested store...')
#2 [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Model/Manager.php(121): EthanYehuda\CronjobManager\Helper\Processor->runJob(1524054352, 1524054352, Array, Object(Magento\Cron\Model\Schedule), 'default')
#3 [store_path]/vendor/ethanyehuda/magento2-cronjobmanager/Controller/Adminhtml/Manage/Job/Dispatch.php(52): EthanYehuda\CronjobManager\Model\Manager->dispatchCron('93203', 'elasticsuite_in...')
#4 [store_path]/generated/code/EthanYehuda/CronjobManager/Controller/Adminhtml/Manage/Job/Dispatch/Interceptor.php(24): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch->execute()
#5 [store_path]/vendor/magento/framework/App/Action/Action.php(107): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->execute()
#6 [store_path]/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 [store_path]/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 [store_path]/vendor/magento/framework/Interception/Interceptor.php(138): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->___callParent('dispatch', Array)
#9 [store_path]/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 [store_path]/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 [store_path]/vendor/magento/framework/Interception/Interceptor.php(153): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 [store_path]/generated/code/EthanYehuda/CronjobManager/Controller/Adminhtml/Manage/Job/Dispatch/Interceptor.php(39): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->___callPlugins('dispatch', Array, NULL)
#13 [store_path]/vendor/magento/framework/App/FrontController.php(55): EthanYehuda\CronjobManager\Controller\Adminhtml\Manage\Job\Dispatch\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#14 [store_path]/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#15 [store_path]/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#16 [store_path]/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [store_path]/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#18 [store_path]/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 [store_path]/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#20 [store_path]/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#21 {main}
```

**Comment by Ethan3600** [comment]
@refueledinc thanks (again) for reporting the issue

Please upgrade to v1.3.4
Released some bug fixes to mitigate this issue.

Let me know if this does the trick

**Comment by refueledinc** [comment]
Yes, that appears to have fixed the issue. Thank you
